[project]
dependencies = [
  "mkdocs-git-revision-date-localized-plugin>=1.4.7",
  "mkdocs-material>=9.5.48",
  "mkdocs>=1.6.1",
]
description = ""
name = "digital-garden"
readme = "README.md"
requires-python = ">=3.12"
version = "0.1.0"

[dependency-groups]
dev = ["pre-commit>=4.3.0"]
